function I_D = uniform_model_text(V_G, V_D, type)

parameters;

if strcmp(type,'N')
    NMOS_parameters;
else
    PMOS_parameters;
end

V_Gx = [num2str(eta),'*',num2str(V_t),'*','log(1+exp((',V_G,'-', ...
    num2str(V_T),')/',num2str(eta),'/',num2str(V_t),'))+',num2str(V_T)];
mu_s = [num2str(mu_0),'/(1+', num2str(theta), '*(', V_Gx, '-', ...
    num2str(V_T),')/(',num2str(alfa),'*',num2str(L),'*', ...
    num2str(v_sat),')))-1)'];
V_Dsat = ['((',num2str(L),'*',num2str(v_sat),'/',num2str(mu_s), ...
    ')*(pow((1+2*',num2str(mu_s),'/',num2str(alfa),'/',num2str(L), ...
    '/',num2str(v_sat),'*(',V_Gx,'-',num2str(V_T),')),0.5)-1))'];
l_d = [num2str(L),'*log(1+(',num2str(V_D),'-',num2str(V_Dsat),')/', ...
    num2str(V_P),')'];
V_Dx = [V_Dsat,'*(1-log(1+exp(',num2str(A),'*(1-',V_D,'/', ...
    V_Dsat,')))/',num2str(B),')'];
I_D = [num2str(W),'*',num2str(mu_s),'*',num2str(C_ox),'/(', ...
    num2str(L),'-',l_d,')/(1+',V_Dx,'*',num2str(mu_s),'/(', ...
    num2str(L),'-',l_d,')/',num2str(v_sat),')*(',V_Gx,'-', ...
    num2str(V_T),'-0.5*',num2str(alfa),'*',V_Dx,')*',V_Dx];